### ISSUE TITLE
Error from QE output to dpdata, "IndexError: index 377 is out of bounds for axis 0 with size 377"

### ISSUE THREAD

**Issue by zhouyium** [deepmodeling/SC21_DP_Tutorial#2]
Dear all:
      According to https://developer.nvidia.com/blog/accelerated-molecular-simulation-using-deep-potential-workflow-with-ngc/ this page. Here is something wrong.
1. AIMD simulation. from this page the command line is 
   `cp.x < c.md98.cp.in`
but in this github resporisty, there has not c.md98.cp.in. But I can run the SC21_DP_Tutorial/AIMD/QE/run.sh to finish the AIMD simulation.
2. Training data preparation
    After run python3 logtodata.py, the follwing is problem
`/SC21_DP_Tutorial/AIMD/QE$ python3 logtodata.py
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (2.0.2) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "logtodata.py", line 3, in <module>
    d_log = dpdata.LabeledSystem('graphene', fmt = 'qe/cp/traj')
  File "/home/yizhou/.local/lib/python3.8/site-packages/dpdata/system.py", line 281, in __init__
    self.from_fmt(
  File "/home/yizhou/.local/lib/python3.8/site-packages/dpdata/system.py", line 318, in from_fmt
    return self.from_fmt_obj(load_format(fmt), file_name, **kwargs)
  File "/home/yizhou/.local/lib/python3.8/site-packages/dpdata/system.py", line 1162, in from_fmt_obj
    data = fmtobj.from_labeled_system(file_name, **kwargs)
  File "/home/yizhou/.local/lib/python3.8/site-packages/dpdata/plugins/qe.py", line 22, in from_labeled_system
    data, cs = dpdata.qe.traj.to_system_data(
  File "/home/yizhou/.local/lib/python3.8/site-packages/dpdata/qe/traj.py", line 196, in to_system_data
    data["coords"], csteps = load_data(
  File "/home/yizhou/.local/lib/python3.8/site-packages/dpdata/qe/traj.py", line 132, in load_data
    with open(fname) as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'graphene.pos'
`
How to fix this problem.

**Comment by zhouyium** [comment]
Sorry Guys, I DO not run the copy.sh, after run the copy.sh.
The error change to "IndexError: index 377 is out of bounds for axis 0 with size 377"
`SC21_DP_Tutorial/AIMD/QE$bash ./run.sh
cd out
SC21_DP_Tutorial/AIMD/QE/out$ python logtodata.py
Data Summary
Labeled System
-------------------
Frame Numbers      : 377
Atom Numbers       : 98
Including Virials  : No
Element List       :
-------------------
C
98
200
Traceback (most recent call last):
  File "logtodata.py", line 12, in <module>
    print(d_log_shuffled.sub_system(np.arange(i*Neach, (i+1)*Neach).tolist()).get_nframes())
  File "/home/yizhou/.local/lib/python3.8/site-packages/dpdata/system.py", line 505, in sub_system
    tmp.data[tt.name] = self.data[tt.name][tuple(new_shape)]
IndexError: index 377 is out of bounds for axis 0 with size 377
`
The following is my ubuntu.
Ubuntu : 20.04
Conda: 2023.03-1-Linux-x86_64
DeepMD:  using coda install the cpu version with python 3.8
python: 3.8.16
